# Generated by Django 5.0.2 on 2024-02-15 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 15, 21, 10, 5, 526031)),
        ),
    ]
