# Generated by Django 5.0.2 on 2024-02-15 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_info_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 15, 21, 11, 28, 121936)),
        ),
    ]
