# Generated by Django 5.0.3 on 2024-03-15 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='age',
        ),
        migrations.RemoveField(
            model_name='info',
            name='date',
        ),
        migrations.RemoveField(
            model_name='info',
            name='image',
        ),
    ]
