# Generated by Django 5.0.3 on 2024-03-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_info_use_info_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('salary', models.IntegerField()),
                ('image', models.ImageField(upload_to='uploads/info/')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.condition')),
                ('user', models.ManyToManyField(to='web.info')),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='jobs',
            field=models.ManyToManyField(to='web.job'),
        ),
    ]
