# Generated by Django 5.0.3 on 2024-03-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_job_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
