# Generated by Django 5.0.3 on 2024-03-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hour',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='place',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
    ]
